language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install: "pip install ."
before_script:
  - wget 'https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip'
  - unzip "0.5.0_linux_amd64.zip"
  - ./consul --version
  - ./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &
  - sleep 5
script:
  - nosetests
